Update README.md
hachi-sandbox/git-training pull request #15
Opened 2016-01-12 14:58 UTC by hachi-sandbox

届く？

2016-01-12 15:00 UTC, hachi-sandbox commented
あああ

2016-01-12 15:01 UTC, hachi-sandbox commented
aaaa

2016-01-12 15:06 UTC, hachi-sandbox commented
@hachi-eiji pls review

2016-09-15 00:58 UTC, hachi-eiji commented on README.md
> -ほげ
ほげほげ

2016-09-15 00:59 UTC, hachi-eiji commented on README.md
> -ほげ
ふがふが

2016-09-15 00:59 UTC, hachi-eiji requested changes
これどうよ？？

2016-09-15 01:45 UTC, hachi-eiji commented on README.md
> -ほげ
ああそれねー

2016-09-15 01:45 UTC, hachi-eiji commented on README.md
> -ほげ
ああ、これね

2016-09-15 01:45 UTC, hachi-eiji commented on README.md
>  add more comment
これけさなくていいの？

2016-09-15 01:46 UTC, hachi-eiji approved these changes
lgtm

2016-09-15 01:47 UTC, hachi-eiji commented on README.md
>  add comment
これはちょっとつらいかも

2016-09-15 01:47 UTC, hachi-eiji approved these changes
okっす

2016-09-15 12:17 UTC, hachi-eiji requested changes
これこれ

2016-09-15 12:17 UTC, hachi-eiji approved these changes
あれあれ

2016-09-15 12:20 UTC, hachi-sandbox commented on README.md
> -ほげ
せやね

2016-09-15 12:20 UTC, hachi-sandbox commented on README.md
> -ほげ
そうそう

2016-09-15 12:20 UTC, hachi-sandbox reviewed
せやな

2016-09-15 12:21 UTC, hachi-sandbox commented on README.md
>  add more comment
あ、はい

2016-09-15 12:21 UTC, hachi-sandbox commented on README.md
> -ほげ
そうっす

2016-09-15 12:21 UTC, hachi-sandbox commented on README.md
> -ほげ
okok

2016-09-15 12:21 UTC, hachi-sandbox reviewed
かきましたー

2016-09-27 09:14 UTC, closed without merging